[package]
name = "termpause"
version = "0.1.0"
edition = "2021"
authors=["fromgodd"]
description = "Simple interruption for console"
license = "MIT"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
